netbox/core/api/urls.py
from netbox.api.routers import NetBoxRouter
from . import views

app_name = 'core-api'

router = NetBoxRouter()
router.APIRootView = views.CoreRootView

router.register('data-sources', views.DataSourceViewSet)
router.register('data-files', views.DataFileViewSet)
router.register('jobs', views.JobViewSet)
router.register('object-changes', views.ObjectChangeViewSet, basename='objectchange')
router.register('object-types', views.ObjectTypeViewSet)
router.register('background-queues', views.BackgroundQueueViewSet, basename='rqqueue')
router.register('background-workers', views.BackgroundWorkerViewSet, basename='rqworker')
router.register('background-tasks', views.BackgroundTaskViewSet, basename='rqtask')

urlpatterns = router.urls

netbox/core/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views

app_name = 'core'
urlpatterns = (

    path('data-sources/', include(get_model_urls('core', 'datasource', detail=False))),
    path('data-sources/<int:pk>/', include(get_model_urls('core', 'datasource'))),

    path('data-files/', include(get_model_urls('core', 'datafile', detail=False))),
    path('data-files/<int:pk>/', include(get_model_urls('core', 'datafile'))),

    path('jobs/', include(get_model_urls('core', 'job', detail=False))),
    path('jobs/<int:pk>/', include(get_model_urls('core', 'job'))),

    path('changelog/', include(get_model_urls('core', 'objectchange', detail=False))),
    path('changelog/<int:pk>/', include(get_model_urls('core', 'objectchange'))),

    # Background Tasks
    path('background-queues/', views.BackgroundQueueListView.as_view(), name='background_queue_list'),
    path(
        'background-queues/<int:queue_index>/<str:status>/',
        views.BackgroundTaskListView.as_view(),
        name='background_task_list'
    ),
    path('background-tasks/<str:job_id>/', views.BackgroundTaskView.as_view(), name='background_task'),
    path(
        'background-tasks/<str:job_id>/delete/',
        views.BackgroundTaskDeleteView.as_view(),
        name='background_task_delete'
    ),
    path(
        'background-tasks/<str:job_id>/requeue/',
        views.BackgroundTaskRequeueView.as_view(),
        name='background_task_requeue'
    ),
    path(
        'background-tasks/<str:job_id>/enqueue/',
        views.BackgroundTaskEnqueueView.as_view(),
        name='background_task_enqueue'
    ),
    path('background-tasks/<str:job_id>/stop/', views.BackgroundTaskStopView.as_view(), name='background_task_stop'),
    path('background-workers/<int:queue_index>/', views.WorkerListView.as_view(), name='worker_list'),
    path('background-workers/<str:key>/', views.WorkerView.as_view(), name='worker'),

    path('config-revisions/', include(get_model_urls('core', 'configrevision', detail=False))),
    path('config-revisions/<int:pk>/', include(get_model_urls('core', 'configrevision'))),

    path('system/', views.SystemView.as_view(), name='system'),

    path('plugins/', views.PluginListView.as_view(), name='plugin_list'),
    path('plugins/<str:name>/', views.PluginView.as_view(), name='plugin'),
)

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.views.decorators.cache import cache_page
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from account.views import LoginView, LogoutView
from netbox.api.views import APIRootView, StatusView
from netbox.graphql.schema import schema
from netbox.graphql.views import NetBoxGraphQLView
from netbox.plugins.urls import plugin_patterns, plugin_api_patterns
from netbox.views import HomeView, MediaView, StaticMediaFailureView, SearchView, htmx

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('oauth/', include('social_django.urls', namespace='social')),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('core/', include('core.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('users/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),
    path('vpn/', include('vpn.urls')),
    path('wireless/', include('wireless.urls')),

    # Current user views
    path('user/', include('account.urls')),

    # HTMX views
    path('htmx/object-selector/', htmx.ObjectSelectorView.as_view(), name='htmx_object_selector'),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/core/', include('core.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/vpn/', include('vpn.api.urls')),
    path('api/wireless/', include('wireless.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),

    path(
        "api/schema/",
        cache_page(timeout=86400, key_prefix=f"api_schema_{settings.RELEASE.version}")(
            SpectacularAPIView.as_view()
        ),
        name="schema",
    ),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='api_docs'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='api_redocs'),

    # GraphQL
    path('graphql/', NetBoxGraphQLView.as_view(schema=schema), name='graphql'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', MediaView.as_view(), name='media'),
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),
]

# django-debug-toolbar
if settings.DEBUG:
    import debug_toolbar
    _patterns.append(path('__debug__/', include(debug_toolbar.urls)))

# Prometheus metrics
if settings.METRICS_ENABLED:
    _patterns.append(path('', include('django_prometheus.urls')))

# Prepend BASE_PATH
urlpatterns = [
    path(settings.BASE_PATH, include(_patterns))
]

handler404 = 'netbox.views.errors.handler_404'
handler500 = 'netbox.views.errors.handler_500'

netbox/vpn/urls.py
from django.urls import include, path

from utilities.urls import get_model_urls
from . import views  # noqa F401

app_name = 'vpn'
urlpatterns = [

    path('tunnel-groups/', include(get_model_urls('vpn', 'tunnelgroup', detail=False))),
    path('tunnel-groups/<int:pk>/', include(get_model_urls('vpn', 'tunnelgroup'))),

    path('tunnels/', include(get_model_urls('vpn', 'tunnel', detail=False))),
    path('tunnels/<int:pk>/', include(get_model_urls('vpn', 'tunnel'))),

    path('tunnel-terminations/', include(get_model_urls('vpn', 'tunneltermination', detail=False))),
    path('tunnel-terminations/<int:pk>/', include(get_model_urls('vpn', 'tunneltermination'))),

    path('ike-proposals/', include(get_model_urls('vpn', 'ikeproposal', detail=False))),
    path('ike-proposals/<int:pk>/', include(get_model_urls('vpn', 'ikeproposal'))),

    path('ike-policies/', include(get_model_urls('vpn', 'ikepolicy', detail=False))),
    path('ike-policies/<int:pk>/', include(get_model_urls('vpn', 'ikepolicy'))),

    path('ipsec-proposals/', include(get_model_urls('vpn', 'ipsecproposal', detail=False))),
    path('ipsec-proposals/<int:pk>/', include(get_model_urls('vpn', 'ipsecproposal'))),

    path('ipsec-policies/', include(get_model_urls('vpn', 'ipsecpolicy', detail=False))),
    path('ipsec-policies/<int:pk>/', include(get_model_urls('vpn', 'ipsecpolicy'))),

    path('ipsec-profiles/', include(get_model_urls('vpn', 'ipsecprofile', detail=False))),
    path('ipsec-profiles/<int:pk>/', include(get_model_urls('vpn', 'ipsecprofile'))),

    path('l2vpns/', include(get_model_urls('vpn', 'l2vpn', detail=False))),
    path('l2vpns/<int:pk>/', include(get_model_urls('vpn', 'l2vpn'))),

    path('l2vpn-terminations/', include(get_model_urls('vpn', 'l2vpntermination', detail=False))),
    path('l2vpn-terminations/<int:pk>/', include(get_model_urls('vpn', 'l2vpntermination'))),

]

netbox/core/models/change_logging.py
from functools import cached_property

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel

from core.choices import ObjectChangeActionChoices
from core.querysets import ObjectChangeQuerySet
from netbox.models.features import ChangeLoggingMixin
from netbox.models.features import has_feature
from utilities.data import shallow_compare_dict

__all__ = (
    'ObjectChange',
)


class ObjectChange(models.Model):
    """
    Record a change to an object and the user account associated with that change. A change record may optionally
    indicate an object related to the one being changed. For example, a change to an interface may also indicate the
    parent device. This will ensure changes made to component models appear in the parent model's changelog.
    """
    time = models.DateTimeField(
        verbose_name=_('time'),
        auto_now_add=True,
        editable=False,
        db_index=True
    )
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name='changes',
        blank=True,
        null=True
    )
    user_name = models.CharField(
        verbose_name=_('user name'),
        max_length=150,
        editable=False
    )
    request_id = models.UUIDField(
        verbose_name=_('request ID'),
        editable=False,
        db_index=True
    )
    action = models.CharField(
        verbose_name=_('action'),
        max_length=50,
        choices=ObjectChangeActionChoices
    )
    changed_object_type = models.ForeignKey(
        to='contenttypes.ContentType',
        on_delete=models.PROTECT,
        related_name='+'
    )
    changed_object_id = models.PositiveBigIntegerField()
    changed_object = GenericForeignKey(
        ct_field='changed_object_type',
        fk_field='changed_object_id'
    )
    related_object_type = models.ForeignKey(
        to='contenttypes.ContentType',
        on_delete=models.PROTECT,
        related_name='+',
        blank=True,
        null=True
    )
    related_object_id = models.PositiveBigIntegerField(
        blank=True,
        null=True
    )
    related_object = GenericForeignKey(
        ct_field='related_object_type',
        fk_field='related_object_id'
    )
    object_repr = models.CharField(
        max_length=200,
        editable=False
    )
    message = models.CharField(
        verbose_name=_('message'),
        max_length=200,
        editable=False,
        blank=True
    )
    prechange_data = models.JSONField(
        verbose_name=_('pre-change data'),
        editable=False,
        blank=True,
        null=True
    )
    postchange_data = models.JSONField(
        verbose_name=_('post-change data'),
        editable=False,
        blank=True,
        null=True
    )

    objects = ObjectChangeQuerySet.as_manager()

    class Meta:
        ordering = ['-time']
        indexes = (
            models.Index(fields=('changed_object_type', 'changed_object_id')),
            models.Index(fields=('related_object_type', 'related_object_id')),
        )
        verbose_name = _('object change')
        verbose_name_plural = _('object changes')

    def __str__(self):
        return '{} {} {} by {}'.format(
            self.changed_object_type,
            self.object_repr,
            self.get_action_display().lower(),
            self.user_name
        )

    def clean(self):
        super().clean()

        # Validate the assigned object type
        if not has_feature(self.changed_object_type, 'change_logging'):
            raise ValidationError(
                _("Change logging is not supported for this object type ({type}).").format(
                    type=self.changed_object_type
                )
            )

    def save(self, *args, **kwargs):

        # Record the user's name and the object's representation as static strings
        if not self.user_name:
            self.user_name = self.user.username
        if not self.object_repr:
            self.object_repr = str(self.changed_object)

        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('core:objectchange', args=[self.pk])

    def get_action_color(self):
        return ObjectChangeActionChoices.colors.get(self.action)

    @cached_property
    def has_changes(self):
        return self.prechange_data != self.postchange_data

    @cached_property
    def diff_exclude_fields(self):
        """
        Return a set of attributes which should be ignored when calculating a diff
        between the pre- and post-change data. (For instance, it would not make
        sense to compare the "last updated" times as these are expected to differ.)
        """
        model = self.changed_object_type.model_class()
        attrs = set()

        # Exclude auto-populated change tracking fields
        if issubclass(model, ChangeLoggingMixin):
            attrs.update({'created', 'last_updated'})

        # Exclude MPTT-internal fields
        if issubclass(model, MPTTModel):
            attrs.update({'level', 'lft', 'rght', 'tree_id'})

        return attrs

    def get_clean_data(self, prefix):
        """
        Return only the pre-/post-change attributes which are relevant for calculating a diff.
        """
        ret = {}
        change_data = getattr(self, f'{prefix}_data') or {}
        for k, v in change_data.items():
            if k not in self.diff_exclude_fields and not k.startswith('_'):
                ret[k] = v
        return ret

    @cached_property
    def prechange_data_clean(self):
        return self.get_clean_data('prechange')

    @cached_property
    def postchange_data_clean(self):
        return self.get_clean_data('postchange')

    def diff(self):
        """
        Return a dictionary of pre- and post-change values for attributes which have changed.
        """
        prechange_data = self.prechange_data_clean
        postchange_data = self.postchange_data_clean

        # Determine which attributes have changed
        if self.action == ObjectChangeActionChoices.ACTION_CREATE:
            changed_attrs = sorted(postchange_data.keys())
        elif self.action == ObjectChangeActionChoices.ACTION_DELETE:
            changed_attrs = sorted(prechange_data.keys())
        else:
            # TODO: Support deep (recursive) comparison
            changed_data = shallow_compare_dict(prechange_data, postchange_data)
            changed_attrs = sorted(changed_data.keys())

        return {
            'pre': {
                k: prechange_data.get(k) for k in changed_attrs
            },
            'post': {
                k: postchange_data.get(k) for k in changed_attrs
            },
        }

netbox/core/models/config.py
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext, gettext_lazy as _

from utilities.querysets import RestrictedQuerySet

__all__ = (
    'ConfigRevision',
)


class ConfigRevision(models.Model):
    """
    An atomic revision of NetBox's configuration.
    """
    created = models.DateTimeField(
        verbose_name=_('created'),
        auto_now_add=True
    )
    comment = models.CharField(
        verbose_name=_('comment'),
        max_length=200,
        blank=True
    )
    data = models.JSONField(
        blank=True,
        null=True,
        verbose_name=_('configuration data')
    )

    objects = RestrictedQuerySet.as_manager()

    class Meta:
        ordering = ['-created']
        verbose_name = _('config revision')
        verbose_name_plural = _('config revisions')

    def __str__(self):
        if not self.pk:
            return gettext('Default configuration')
        if self.is_active:
            return gettext('Current configuration')
        return gettext('Config revision #{id}').format(id=self.pk)

    def __getattr__(self, item):
        if self.data and item in self.data:
            return self.data[item]
        return super().__getattribute__(item)

    def get_absolute_url(self):
        if not self.pk:
            return reverse('core:config')  # Default config view
        return reverse('core:configrevision', args=[self.pk])

    def activate(self):
        """
        Cache the configuration data.
        """
        cache.set('config', self.data, None)
        cache.set('config_version', self.pk, None)
    activate.alters_data = True

    @property
    def is_active(self):
        return cache.get('config_version') == self.pk

netbox/core/forms/bulk_import.py
from core.models import *
from netbox.forms import NetBoxModelImportForm

__all__ = (
    'DataSourceImportForm',
)


class DataSourceImportForm(NetBoxModelImportForm):

    class Meta:
        model = DataSource
        fields = (
            'name', 'type', 'source_url', 'enabled', 'description', 'sync_interval', 'parameters', 'ignore_rules',
            'comments',
        )

netbox/templates/core/configrevision.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load custom_links %}
{% load helpers %}
{% load perms %}
{% load plugins %}
{% load static %}
{% load i18n %}

{% block breadcrumbs %}
{% endblock %}

{% block control-buttons %}
  {% if not object.pk or object.is_active and perms.core.add_configrevision %}
    {% url 'core:configrevision_add' as edit_url %}
    {% include "buttons/edit.html" with url=edit_url %}
  {% endif %}
  {% if object.pk and not object.is_active and perms.core.delete_configrevision %}
    {% delete_button object %}
  {% endif %}
{% endblock control-buttons %}

{% block subtitle %}
  {% if object.created %}
    <div class="text-secondary fs-5">
      {% trans "Created" %} {{ object.created|isodatetime }}
    </div>
  {% endif %}
{% endblock subtitle %}

{% block content %}
  <div class="row">
    <div class="col col-md-12">
      <div class="card">
        <h2 class="card-header">{% trans "Configuration Data" %}</h2>
        {% include 'core/inc/config_data.html' with config=object.data %}
      </div>

      <div class="card">
        <h2 class="card-header">{% trans "Comment" %}</h2>
        <div class="card-body">
          {{ object.comment|placeholder }}
        </div>
      </div>

    </div>
  </div>
{% endblock %}

netbox/templates/core/configrevision_restore.html
{% extends 'generic/object.html' %}
{% load helpers %}
{% load buttons %}
{% load perms %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Restore" %}: {{ object }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    {% trans "Created" %} {{ object.created|isodatetime }}
  </div>
{% endblock %}

{% block control-buttons %}
  {% if request.user|can_delete:job %}
    {% delete_button job %}
  {% endif %}
{% endblock control-buttons %}

{% block tabs %}
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a href="#log" role="tab" data-bs-toggle="tab" class="nav-link active">{% trans "Restore" %}</a>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">{% trans "Parameter" %}</th>
            <th scope="col">{% trans "Current Value" %}</th>
            <th scope="col">{% trans "New Value" %}</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for param, current, new in params %}
            <tr{% if current != new %} class="table-warning"{% endif %}>
              <td>{{ param }}</td>
              <td>{{ current }}</td>
              <td>{{ new }}</td>
              <td>
                {% if current != new %}
                  <i class="mdi mdi-pencil text-warning" title="{% trans "Changed" %}"></i>
                {% endif %}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <form method="post">
    {% csrf_token %}
    <div class="text-end my-3">
      <a href="{% url 'core:configrevision_list' %}" id="cancel" name="cancel" class="btn btn-outline-secondary">{% trans "Cancel" %}</a>
      <button type="submit" name="restore" class="btn btn-primary">{% trans "Restore" %}</button>
    </div>
  </form>

{% endblock content %}

{% block modals %}
{% endblock modals %}

netbox/templates/core/rq_task.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load buttons %}
{% load helpers %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  <li class="breadcrumb-item"><a href="{% url 'core:background_queue_list' %}">{% trans 'Background Tasks' %}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'core:background_task_list' queue_index=queue_index status=job.get_status %}">{{ queue.name }}</a></li>
{% endblock breadcrumbs %}

{% block title %}{% trans "Job" %} {{ job.id }}{% endblock %}

{% block subtitle %}
  <div class="text-secondary fs-5">
    <span>{% trans "Created" %} {{ job.created_at|isodatetime }}</span>
  </div>
{% endblock subtitle %}

{% block object_identifier %}{% endblock %}

{% block controls %}
  <div class="btn-list mb-2">
    {% url 'core:background_task_delete' job_id=job.id as delete_url %}
    {% include "buttons/delete.html" with url=delete_url %}

    {% if job.is_started %}
      <a href="{% url 'core:background_task_stop' job.id %}" class="btn btn-primary">
        <i class="mdi mdi-stop-circle-outline"></i> {% trans "Stop" %}
      </a>
    {% endif %}
    {% if job.is_failed %}
      <a href="{% url 'core:background_task_requeue' job.id %}" class="btn btn-primary">
        <i class="mdi mdi-sync"></i> {% trans "Requeue" %}
      </a>
    {% endif %}
    {% if not job.is_queued and not job.is_failed %}
      <a href="{% url 'core:background_task_enqueue' job.id %}" class="btn btn-primary">
        <i class="mdi mdi-sync"></i> {% trans "Enqueue" %}
      </a>
    {% endif %}

  </div>
{% endblock controls %}

{% block tabs %}
  <ul class="nav nav-tabs">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" role="tab">{% trans "Job" %}</a>
    </li>
  </ul>
{% endblock tabs %}

{% block content %}
  <div class="row">
    <div class="col col-md-12">
      <div class="card">
        <h2 class="card-header">{% trans "Job" %}</h2>
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">{% trans "Queue" %}</th>
            <td>{{ job.origin|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Timeout" %}</th>
            <td>{{ job.timeout|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Result TTL" %}</th>
            <td>{{ job.result_ttl|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Created" %}</th>
            <td>{{ job.created_at|isodatetime }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Queued" %}</th>
            <td>{{ job.enqueued_at|isodatetime }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Status" %}</th>
            <td>{{ job.get_status|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Callable" %}</th>
            <td>{{ object.get_type_display|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Meta" %}</th>
            <td>{{ job.meta|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Arguments" %}</th>
            <td>{{ jobs.args|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">{% trans "Keyword Arguments" %}</th>
            {# TODO: Render as formatted JSON #}
            <td>{{ job.kwargs }}</td>
          </tr>
          {% if dependency_id %}
            <tr>
              <th scope="row">{% trans "Depends on" %}</th>
              <td><a href="{% url 'core:background_task' job.id %}">{{ dependency_id }}</a></td>
            </tr>
          {% endif %}
          {% if exc_info %}
            <tr>
              <th scope="row">{% trans "Exception" %}</th>
              <td><pre>{% if job.exc_info %}{{ job.exc_info|linebreaks }}{% endif %}</pre></td>
            </tr>
          {% endif %}
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

netbox/templates/core/rq_task_list.html
{% extends 'generic/object_list.html' %}
{% load buttons %}
{% load helpers %}
{% load i18n %}
{% load render_table from django_tables2 %}

{% block page-header %}
  <div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mt-2">
      {# Breadcrumbs #}
      <nav class="breadcrumb-container" aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'core:background_queue_list' %}">{% trans 'Background Queues' %}</a>
          </li>
          <li class="breadcrumb-item">{{ queue.name }}</li>
        </ol>
      </nav>
    </div>
    <div class="row">
      <div class="col">
        <h2 class="page-title mt-2">{% trans 'Background Tasks' %}</h2>
      </div>
    </div>
  </div>
{% endblock page-header %}

{% block title %}{{ status|capfirst }} {% trans "tasks in " %}{{ queue.name }}{% endblock %}

{% block tabs %}
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" role="tab">{% trans "Queued Jobs" %}</a>
    </li>
  </ul>
{% endblock tabs %}

{% block content %}

    {# Object list tab #}
    <div class="tab-pane show active" id="object-list" role="tabpanel" aria-labelledby="object-list-tab">

      {# Object table controls #}
      {% include 'inc/table_controls_htmx.html' with table_modal="ObjectTable_config" %}

      <form method="post" class="form form-horizontal">
        {% csrf_token %}
        {# "Select all" form #}
        {% if table.paginator.num_pages > 1 %}
          <div id="select-all-box" class="d-none card d-print-none">
            <div class="form col-md-12">
              <div class="card-body">
                <div class="float-end">
                  {% if 'bulk_edit' in actions %}
                    {% bulk_edit_button model query_params=request.GET %}
                  {% endif %}
                  {% if 'bulk_delete' in actions %}
                    {% bulk_delete_button model query_params=request.GET %}
                  {% endif %}
                </div>
                <div class="form-check">
                  <input type="checkbox" id="select-all" name="_all" class="form-check-input" />
                  <label for="select-all" class="form-check-label">
                    {% blocktrans trimmed with count=table.rows|length object_type_plural=table.data.verbose_name_plural %}
                      Select <strong>all {{ count }} {{ object_type_plural }}</strong> matching query
                    {% endblocktrans %}
                  </label>
                </div>
              </div>
            </div>
          </div>
        {% endif %}

        <div class="form form-horizontal">
          {% csrf_token %}
          <input type="hidden" name="return_url" value="{% if return_url %}{{ return_url }}{% else %}{{ request.path }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}{% endif %}" />

          {# Objects table #}
          <div class="card">
            <div class="htmx-container table-responsive" id="object_list">
              {% include 'htmx/table.html' %}
            </div>
          </div>
          {# /Objects table #}

          {# Form buttons #}
          <div class="btn-list d-print-none mt-2">
            {% block bulk_buttons %}
              {% if 'bulk_edit' in actions %}
                {% bulk_edit_button model query_params=request.GET %}
              {% endif %}
              {% if 'bulk_delete' in actions %}
                {% bulk_delete_button model query_params=request.GET %}
              {% endif %}
            {% endblock %}
          </div>
          {# /Form buttons #}

        </div>
      </form>
    </div>
    {# /Object list tab #}

{% endblock content %}